<?php

namespace Database\Seeders\ChartOfAccounts;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubLedgerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parent110 = DB::table('chart_of_accounts')->where('code', 110)->value('id');
        $parent111 = DB::table('chart_of_accounts')->where('code', 111)->value('id');
        $parent112 = DB::table('chart_of_accounts')->where('code', 112)->value('id');
        $parent113 = DB::table('chart_of_accounts')->where('code', 113)->value('id');
        $parent114 = DB::table('chart_of_accounts')->where('code', 114)->value('id');
        $parent115 = DB::table('chart_of_accounts')->where('code', 115)->value('id');
        $parent116 = DB::table('chart_of_accounts')->where('code', 116)->value('id');
        $parent121 = DB::table('chart_of_accounts')->where('code', 121)->value('id');

        $parent211 = DB::table('chart_of_accounts')->where('code', 211)->value('id');
        $parent212 = DB::table('chart_of_accounts')->where('code', 212)->value('id');
        $parent213 = DB::table('chart_of_accounts')->where('code', 213)->value('id');
        $parent214 = DB::table('chart_of_accounts')->where('code', 214)->value('id');
        $parent215 = DB::table('chart_of_accounts')->where('code', 215)->value('id');
        $parent216 = DB::table('chart_of_accounts')->where('code', 216)->value('id');

        $parent311 = DB::table('chart_of_accounts')->where('code', 311)->value('id');
        $parent312 = DB::table('chart_of_accounts')->where('code', 312)->value('id');
        $parent315 = DB::table('chart_of_accounts')->where('code', 315)->value('id');
        $parent316 = DB::table('chart_of_accounts')->where('code', 316)->value('id');
        $parent318 = DB::table('chart_of_accounts')->where('code', 318)->value('id');
        $parent320 = DB::table('chart_of_accounts')->where('code', 320)->value('id');
        $parent321 = DB::table('chart_of_accounts')->where('code', 321)->value('id');
        $parent322 = DB::table('chart_of_accounts')->where('code', 322)->value('id');
        $parent323 = DB::table('chart_of_accounts')->where('code', 323)->value('id');
        $parent324 = DB::table('chart_of_accounts')->where('code', 324)->value('id');

        $parent411 = DB::table('chart_of_accounts')->where('code', 411)->value('id');
        $parent412 = DB::table('chart_of_accounts')->where('code', 412)->value('id');
        $parent413 = DB::table('chart_of_accounts')->where('code', 413)->value('id');
        $parent414 = DB::table('chart_of_accounts')->where('code', 414)->value('id');
        $parent415 = DB::table('chart_of_accounts')->where('code', 415)->value('id');

        $parent511 = DB::table('chart_of_accounts')->where('code', 511)->value('id');
        $parent512 = DB::table('chart_of_accounts')->where('code', 512)->value('id');
        $parent513 = DB::table('chart_of_accounts')->where('code', 513)->value('id');
        $parent514 = DB::table('chart_of_accounts')->where('code', 514)->value('id');
        $parent516 = DB::table('chart_of_accounts')->where('code', 516)->value('id');

        $parent610 = DB::table('chart_of_accounts')->where('code', 610)->value('id');
        $parent611 = DB::table('chart_of_accounts')->where('code', 611)->value('id');
        $parent612 = DB::table('chart_of_accounts')->where('code', 612)->value('id');
        $parent613 = DB::table('chart_of_accounts')->where('code', 613)->value('id');
        $parent614 = DB::table('chart_of_accounts')->where('code', 614)->value('id');
        $parent616 = DB::table('chart_of_accounts')->where('code', 616)->value('id');
        $parent617 = DB::table('chart_of_accounts')->where('code', 617)->value('id');
        $parent618 = DB::table('chart_of_accounts')->where('code', 618)->value('id');
        $parent619 = DB::table('chart_of_accounts')->where('code', 619)->value('id');

        $parent710 = DB::table('chart_of_accounts')->where('code', 710)->value('id');
        $parent711 = DB::table('chart_of_accounts')->where('code', 711)->value('id');
        $parent712 = DB::table('chart_of_accounts')->where('code', 712)->value('id');
        $parent713 = DB::table('chart_of_accounts')->where('code', 713)->value('id');

        $parent810 = DB::table('chart_of_accounts')->where('code', 810)->value('id');

        $parent910 = DB::table('chart_of_accounts')->where('code', 910)->value('id');

        // insert group of accounts
        DB::table('chart_of_accounts')->upsert(
            [
                ['code' => '110100', 'name' => 'موجودی نزد صندوق', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110101', 'name' => 'موجودی نزد تنخواه گردان', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110102', 'name' => 'موجودی نزد بانک ها', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110103', 'name' => 'وجوه در راه', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110104', 'name' => 'بانک ها (ارزی)', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110105', 'name' => 'مسکوکات', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110106', 'name' => 'اسناد و اوراق بهادار نزد صندوق', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '110107', 'name' => 'موجودی واریز نامه های ارزی', 'level' => 2, 'parent_id' => $parent110],
                ['code' => '111101', 'name' => 'سهام شرکتها پذیرفته شده در بورس', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '111102', 'name' => 'اوراق مشارکت', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '111103', 'name' => 'سرمایه گذاری در سهام سایر شرکتها', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '111104', 'name' => 'سرمایه گذاری در اوراق بهادار', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '111105', 'name' => 'سپرده های سرمایه گذاری کوتاه مدت بانکی', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '111106', 'name' => 'سرمایه گذاری در طرح ها', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '111107', 'name' => 'سپرده ضمانت نامه های بانکی', 'level' => 2, 'parent_id' => $parent111],
                ['code' => '112100', 'name' => 'حساب های دریافتنی تجاری', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112103', 'name' => 'اسناد دریافتنی تجاری', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112105', 'name' => 'اسناد دریافتنی تجاری در جریان وصول', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112106', 'name' => 'اسناد دریافتنی تجاری نزد صندوق', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112107', 'name' => 'ذخیره مطالبات مشکوک الوصول', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112200', 'name' => 'جاری اشخاص- بدهکاران تجاری', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112201', 'name' => 'بدهی فروشگاه', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112202', 'name' => 'جاری اعضاء-بدهکاران تجاری', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112203', 'name' => 'جاری موسسات و شرکتها -بدهکاران تجاری', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '112204', 'name' => 'اسناد دریافتنی تجاری واخواست شده', 'level' => 2, 'parent_id' => $parent112],
                ['code' => '113100', 'name' => 'جاری کارکنان', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113103', 'name' => 'اشخاص حقیقی', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113104', 'name' => 'شرکت ها و موسسات', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113105', 'name' => 'وام های تعاونی', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113106', 'name' => 'کسری انبار', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113108', 'name' => 'هزینه  های آینده', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113109', 'name' => 'استرداد سهام', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113110', 'name' => 'بدهکاران داخلی واحد اعتباری', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113111', 'name' => 'حواله های به عهده شعب', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113112', 'name' => 'سایر بدهکاران واحد اعتباری', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113113', 'name' => 'سپرده های موقت', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113114', 'name' => 'چکهای در جریان وصول', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113115', 'name' => 'مالیات بر ارزش افزوده خرید', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113116', 'name' => 'سایر حسابهای دریافتنی غیر تجاری', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113117', 'name' => 'بدهی خطوط تولید', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113118', 'name' => 'اسناد دریافتنی غیرتجاری در جریان وصول', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113119', 'name' => 'اسناد دریافتنی غیرتجاری نزد صندوق', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113120', 'name' => 'اسناد دریافتنی غیرتجاری واخواست شده', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113121', 'name' => 'خسارات قابل دریافت از بیمه', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113122', 'name' => 'حق العمل کاران', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '113123', 'name' => 'ترخیص کاران گمرکی', 'level' => 2, 'parent_id' => $parent113],
                ['code' => '114100', 'name' => 'موجودی مواد اولیه', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114101', 'name' => 'مصرف مواد اولیه', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114102', 'name' => 'کالای در جریان ساخت', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114103', 'name' => 'کالای ساخته شده', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114104', 'name' => 'بهای تمام شده کالای ساخته شده', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114105', 'name' => 'برگشت از ساخت', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114106', 'name' => 'خرید کالا', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114107', 'name' => 'برگشت از خرید و تخفیفات', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114108', 'name' => 'موجودی اول دوره', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114109', 'name' => 'موجودی پایان دوره', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114110', 'name' => 'بهای تمام شده کالای خریداری شده', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114111', 'name' => 'موجودی کالای امانی ما نزد دیگران', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114112', 'name' => 'مغایرت انبارگردانی', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114113', 'name' => 'موجودی مواد مصرفی و ملزومات اداری', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114114', 'name' => 'موجودی مطبوعات اداری', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '114115', 'name' => 'خرید محصولات توافقی', 'level' => 2, 'parent_id' => $parent114],
                ['code' => '115100', 'name' => 'محصولات تضمینی', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115111', 'name' => 'پیش پرداخت هزینه های جاری', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115112', 'name' => 'پیش پرداخت خرید کالا و مواد اولیه', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115113', 'name' => 'پیش پرداخت اجاره', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115114', 'name' => 'محصولات توافقی', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115115', 'name' => 'سفارشات و اقلام در راه', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115116', 'name' => 'بدهکاران فروش کالای تضمینی', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115117', 'name' => 'اعتبار اسنادی تعهدی (LC)', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115118', 'name' => 'سفارشات کالا', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115119', 'name' => 'سفارشات قطعات و لوازم یدکی', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115120', 'name' => 'سفارش ماشین آلات', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115121', 'name' => 'موجودی تمیر و سفته', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115122', 'name' => 'هزینه های قبل از گشایش اعتبار', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115123', 'name' => 'پیش پرداخت به پیمانکاران', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115124', 'name' => 'پیش پرداخت خرید خدمات', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115125', 'name' => 'پیش پرداخت خرید دارایی غیرجاری', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115126', 'name' => 'پیش پرداخت مالیات بر درآمد', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115127', 'name' => 'پیش پرداخت بیمه دارائیها', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115128', 'name' => 'پیش پرداخت حسابرسی', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115129', 'name' => 'پیش پرداخت مالیات', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115130', 'name' => 'پیش پرداخت هزینه های تحقیق وتوسعه', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115131', 'name' => 'پیش پرداخت هزینه سود وکارمزدوامها', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '115132', 'name' => 'پیش پرداخت بیمه تامین اجتماعی', 'level' => 2, 'parent_id' => $parent115],
                ['code' => '116100', 'name' => 'سپرده بیمه', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116101', 'name' => 'سپرده حسن انجام کار', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116102', 'name' => 'ودایع پرداختی', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116103', 'name' => 'سپرده نزد بانک ها', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116104', 'name' => 'سپرده های گمرکی', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116105', 'name' => 'سپرده شرکت در مزایده', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116106', 'name' => 'سپرده شرکت در مناقصه', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '116107', 'name' => 'سایر سپرده ها', 'level' => 2, 'parent_id' => $parent116],
                ['code' => '121100', 'name' => 'قرض الحسنه', 'level' => 2, 'parent_id' => $parent121],
                ['code' => '121101', 'name' => 'مشارکت', 'level' => 2, 'parent_id' => $parent121],
                ['code' => '121102', 'name' => 'مبادلات', 'level' => 2, 'parent_id' => $parent121],
                ['code' => '121103', 'name' => 'تعهدات', 'level' => 2, 'parent_id' => $parent121],
                ['code' => '211101', 'name' => 'زمین', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211102', 'name' => 'ساختمان', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211103', 'name' => 'تاسیسات', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211104', 'name' => 'ماشین آلات و تجهیزات', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211105', 'name' => 'اثاثیه و منصوبات', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211106', 'name' => 'ابزار آلات', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211107', 'name' => 'وسائل نقلیه', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '211108', 'name' => 'پروژه های در جریان تکمیل', 'level' => 2, 'parent_id' => $parent211],
                ['code' => '212101', 'name' => 'استهلاک ساختمان', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212102', 'name' => 'استهلاک تاسیسات', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212103', 'name' => 'استهلاک اثاثیه و منصوبات', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212104', 'name' => 'استهلاک ابزار آلات', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212105', 'name' => 'استهلاک وسائل نقلیه', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212106', 'name' => 'استهلاک ماشین آلات و تجهیرات', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212107', 'name' => 'استهلاک دارایییهای زیستی مولد', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212108', 'name' => 'استهلاک داراییهای زیستی غیر مولد', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212109', 'name' => 'استهلاک زمینهای کشاورزی', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '212110', 'name' => 'سایر دارائیهای استهلاک پذیر', 'level' => 2, 'parent_id' => $parent212],
                ['code' => '213101', 'name' => 'حق الامتیازها', 'level' => 2, 'parent_id' => $parent213],
                ['code' => '213102', 'name' => 'سرقفلی محل کسب', 'level' => 2, 'parent_id' => $parent213],
                ['code' => '213103', 'name' => 'سایر', 'level' => 2, 'parent_id' => $parent213],
                ['code' => '213104', 'name' => 'نرم افزار ها', 'level' => 2, 'parent_id' => $parent213],
                ['code' => '213105', 'name' => 'سیستم ها و روش ها', 'level' => 2, 'parent_id' => $parent213],
                ['code' => '214101', 'name' => 'سرمایه گذاری در سهام', 'level' => 2, 'parent_id' => $parent214],
                ['code' => '214102', 'name' => 'اوراق مشارکت', 'level' => 2, 'parent_id' => $parent214],
                ['code' => '214103', 'name' => 'سپرده های سرمایه گذاری بلند مدت بانکی', 'level' => 2, 'parent_id' => $parent214],
                ['code' => '214104', 'name' => 'سرمایه گذاری در طرح ها', 'level' => 2, 'parent_id' => $parent214],
                ['code' => '215100', 'name' => 'ساختمان در جریان تکمیل', 'level' => 2, 'parent_id' => $parent215],
                ['code' => '215101', 'name' => 'تاسیسات در جریان تکمیل', 'level' => 2, 'parent_id' => $parent215],
                ['code' => '215102', 'name' => 'ماشین آلات در جریان تکمیل', 'level' => 2, 'parent_id' => $parent215],
                ['code' => '215103', 'name' => 'ابزارآلات در جریان تکمیل', 'level' => 2, 'parent_id' => $parent215],
                ['code' => '216101', 'name' => 'حصه بلند مدت وام کارکنان', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216102', 'name' => 'اسناد دریافتنی بلند مدت', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216103', 'name' => 'وام های اعطایی بلند مدت', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216104', 'name' => 'دارایییهای زیستی مولد', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216105', 'name' => 'داراییهای زیستی غیر مولد', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216106', 'name' => 'مخارج انتقالی به دوره های آتی', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216107', 'name' => 'وجه نقد کنار گذاشته شده برای هدف مشخص', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '216108', 'name' => 'وجه نقد مسدود شده نزد بانک', 'level' => 2, 'parent_id' => $parent216],
                ['code' => '311101', 'name' => 'اسناد پرداختنی تجاری', 'level' => 2, 'parent_id' => $parent311],
                ['code' => '311103', 'name' => 'جاری اشخاص- بستانکاران تجاری', 'level' => 2, 'parent_id' => $parent311],
                ['code' => '311104', 'name' => 'جاری اعضاء-بستانکاران تجاری', 'level' => 2, 'parent_id' => $parent311],
                ['code' => '311105', 'name' => 'جاری موسسات و شرکتها -بستانکاران تجاری', 'level' => 2, 'parent_id' => $parent311],
                ['code' => '311106', 'name' => 'معلق خرید', 'level' => 2, 'parent_id' => $parent311],
                ['code' => '312101', 'name' => 'حسابهای پرداختنی غیر تجاری', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312102', 'name' => 'استقراض از شبکه تعاون روستایی', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312103', 'name' => 'حقوق و دستمزد پرداختی', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312104', 'name' => 'تعهدات وکسورات  تکلیفی - اداره دارایی', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312105', 'name' => 'سپرده های دریافتنی(مناقصه-حسن انجام کار', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312106', 'name' => 'اشخاص حقیقی بستانکاران غیر تجاری', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312107', 'name' => 'اسناد پرداختنی غیر تجاری', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312108', 'name' => 'تعهدات وکسورات  تکلیفی - تامین اجتماعی', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312110', 'name' => 'تعهدات خرید تضمینی', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312111', 'name' => 'ذخیره مطالبات مشکوک الوصول', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312112', 'name' => 'ذخیره کاهش ارزش دائمی سرمایه گذاری ها', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312113', 'name' => 'ذخیره کاهش ارزش موجودی ها', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312114', 'name' => 'سرک انبار', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312115', 'name' => 'شرکتها و مؤسسات بستانکاران غیر تجاری', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312116', 'name' => 'درآمدهای آینده', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312117', 'name' => 'سهام موقت', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312118', 'name' => 'بستانکاران داخلی واحد اعتباری', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312119', 'name' => 'حواله های به عهده ما', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312120', 'name' => 'سایر بستانکاران واحد اعتباری', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312121', 'name' => 'مالیات بر ارزش افزوده فروش', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312122', 'name' => 'درآمد آتی قرض الحسنه', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312123', 'name' => 'درآمد آتی مبادلات', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312124', 'name' => 'درآمد آتی مشارکت', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312125', 'name' => 'درآمد آتی تعهدات', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312126', 'name' => 'دو در هزار فروش صنایع', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312127', 'name' => 'یک در هزار تربیت بدنی', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312128', 'name' => 'پیمانکاران', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '312129', 'name' => 'ذخیره هزینه های معوق پرداخت نشده', 'level' => 2, 'parent_id' => $parent312],
                ['code' => '315101', 'name' => 'پیش دریافت فروش', 'level' => 2, 'parent_id' => $parent315],
                ['code' => '315102', 'name' => 'پیش دریافت ارائه خدمات', 'level' => 2, 'parent_id' => $parent315],
                ['code' => '315103', 'name' => 'سایر پیش دریافتها', 'level' => 2, 'parent_id' => $parent315],
                ['code' => '316101', 'name' => 'بانکهای اعتبار', 'level' => 2, 'parent_id' => $parent316],
                ['code' => '316102', 'name' => 'اعتبارات دریافتی از سازمان مرکزی', 'level' => 2, 'parent_id' => $parent316],
                ['code' => '316103', 'name' => 'اعتبارات دریافتی از موسسات مالی و اعتباری', 'level' => 2, 'parent_id' => $parent316],
                ['code' => '316104', 'name' => 'اعتبارات دریافتی از صندوق توسعه کشاورزی', 'level' => 2, 'parent_id' => $parent316],
                ['code' => '316105', 'name' => 'سایر اعتبارات دریافتی', 'level' => 2, 'parent_id' => $parent316],
                ['code' => '318100', 'name' => 'سود سهام پرداختنی', 'level' => 2, 'parent_id' => $parent318],
                ['code' => '318101', 'name' => 'مازاد برگشتی به اعضاء', 'level' => 2, 'parent_id' => $parent318],
                ['code' => '320100', 'name' => 'ذخیره مالیات بر درآمد شرکتها', 'level' => 2, 'parent_id' => $parent320],
                ['code' => '320101', 'name' => 'سایر ذخایر جاری', 'level' => 2, 'parent_id' => $parent320],
                ['code' => '321100', 'name' => 'سپرده قرض الحسنه پس انداز', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321101', 'name' => 'سپرده قرض الحسنه جاری', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321102', 'name' => 'سپرده سرمایه گذاری کوتاه مدت عادی', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321103', 'name' => 'سپرده سرمایه گذاری کوتاه مدت سه ماهه', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321104', 'name' => 'سپرده سرمایه گذاری کوتاه مدت شش ماهه', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321105', 'name' => 'سپرده سرمایه گذاری کوتاه مدت نه ماهه', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321106', 'name' => 'سپرده سرمایه گذاری بلند مدت یک ساله', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321107', 'name' => 'سپرده سرمایه گذاری بلند مدت دو ساله', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321108', 'name' => 'سپرده سرمایه گذاری بلند مدت سه ساله', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321109', 'name' => 'سپرده سرمایه گذاری بلند مدت چهار ساله', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321110', 'name' => 'سپرده سرمایه گذاری بلند مدت پنج ساله', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '321111', 'name' => 'حساب مضاربه وجوه دریافتی', 'level' => 2, 'parent_id' => $parent321],
                ['code' => '322100', 'name' => 'رابط فروشگاه', 'level' => 2, 'parent_id' => $parent322],
                ['code' => '322101', 'name' => 'رابط خطوط تولید', 'level' => 2, 'parent_id' => $parent322],
                ['code' => '323100', 'name' => 'ذخیره کاهش ارزش موجودی مواد', 'level' => 2, 'parent_id' => $parent323],
                ['code' => '323101', 'name' => 'ذخیره مرخصی استفاده نشده', 'level' => 2, 'parent_id' => $parent323],
                ['code' => '323102', 'name' => 'ذخیره بن کارگری', 'level' => 2, 'parent_id' => $parent323],
                ['code' => '323103', 'name' => 'ذخیره تضمین محصولات', 'level' => 2, 'parent_id' => $parent323],
                ['code' => '323104', 'name' => 'ذخیره کاهش ارزش موجودی کالا', 'level' => 2, 'parent_id' => $parent323],
                ['code' => '324100', 'name' => 'سپرده حسن انجام کار', 'level' => 2, 'parent_id' => $parent324],
                ['code' => '324101', 'name' => 'سپرده دریافتی مزایده', 'level' => 2, 'parent_id' => $parent324],
                ['code' => '324102', 'name' => 'سپرده دریافتی مناقصه', 'level' => 2, 'parent_id' => $parent324],
                ['code' => '324103', 'name' => 'ودایع دریافتی', 'level' => 2, 'parent_id' => $parent324],
                ['code' => '324104', 'name' => 'سپرده حسن اجرای تعهدات', 'level' => 2, 'parent_id' => $parent324],
                ['code' => '411101', 'name' => 'حسابهای پرداختنی بلند مدت تجاری', 'level' => 2, 'parent_id' => $parent411],
                ['code' => '411102', 'name' => 'چکهای پرداختنی بلند مدت', 'level' => 2, 'parent_id' => $parent411],
                ['code' => '411103', 'name' => 'اسناد پرداختنی بلند مدت  تجاری', 'level' => 2, 'parent_id' => $parent411],
                ['code' => '412101', 'name' => 'اعتبارات بلند مدت بانکی', 'level' => 2, 'parent_id' => $parent412],
                ['code' => '412102', 'name' => 'اعتبارات بلند مدت سازمان', 'level' => 2, 'parent_id' => $parent412],
                ['code' => '412103', 'name' => 'اعتبارات بلند مدت مؤسسات تأمین مالی', 'level' => 2, 'parent_id' => $parent412],
                ['code' => '413100', 'name' => 'سود ناشی از تسعیر بدهیهای بلند مدت ارزی', 'level' => 2, 'parent_id' => $parent413],
                ['code' => '413101', 'name' => 'دارایی های اهدایی از طرف اشخاص', 'level' => 2, 'parent_id' => $parent413],
                ['code' => '414101', 'name' => 'ذخیره مزایای خدمت کارکنان', 'level' => 2, 'parent_id' => $parent414],
                ['code' => '415100', 'name' => 'حسابهای پرداختنی بلند مدت غیر تجاری', 'level' => 2, 'parent_id' => $parent415],
                ['code' => '415101', 'name' => 'اسناد پرداختنی بلند مدت  غیر تجاری', 'level' => 2, 'parent_id' => $parent415],
                ['code' => '511101', 'name' => 'سرمایه سهام', 'level' => 2, 'parent_id' => $parent511],
                ['code' => '511102', 'name' => 'صرف', 'level' => 2, 'parent_id' => $parent511],
                ['code' => '511103', 'name' => 'سرمایه تعهد شده', 'level' => 2, 'parent_id' => $parent511],
                ['code' => '511104', 'name' => 'سرمایه اهدایی', 'level' => 2, 'parent_id' => $parent511],
                ['code' => '511105', 'name' => 'امتیاز پاره سهم (سهام غیر رند)', 'level' => 2, 'parent_id' => $parent511],
                ['code' => '512101', 'name' => 'ذخیره قانونی (تقسیم سود ویژه )', 'level' => 2, 'parent_id' => $parent512],
                ['code' => '512102', 'name' => 'ذخیره قانونی (فروش داراییهای ثابت)', 'level' => 2, 'parent_id' => $parent512],
                ['code' => '512103', 'name' => 'ذخیره قانونی (هدایا)', 'level' => 2, 'parent_id' => $parent512],
                ['code' => '512104', 'name' => 'ذخیره قانونی (درآمدهای مجاز عملیات جاری)', 'level' => 2, 'parent_id' => $parent512],
                ['code' => '513101', 'name' => 'ذخیره اختیاری', 'level' => 2, 'parent_id' => $parent513],
                ['code' => '513102', 'name' => 'ذخیره احتیاطی', 'level' => 2, 'parent_id' => $parent513],
                ['code' => '513103', 'name' => 'ذخیره واحد اعتباری', 'level' => 2, 'parent_id' => $parent513],
                ['code' => '514101', 'name' => 'مازاد تجدید ارزیابی دارایی ها', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514102', 'name' => 'زمین', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514103', 'name' => 'ساختمان', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514104', 'name' => 'تاسیسات', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514105', 'name' => 'ماشین آلات و تجهیزات', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514106', 'name' => 'ابزار آلات', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514107', 'name' => 'وسایل نقلیه', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514108', 'name' => 'اثاثیه و منصوبات', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514109', 'name' => 'دارایی های سرمایه ای موجود در انبار', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514110', 'name' => 'سرمای گذاری در سهام شرکتهای تابعه', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514111', 'name' => 'سرمایه گذاری در سهام سایر شرکتها', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '514112', 'name' => 'سرمایه گذاری در اوراق مشارکت', 'level' => 2, 'parent_id' => $parent514],
                ['code' => '516100', 'name' => 'سود و زیان انباشته', 'level' => 2, 'parent_id' => $parent516],
                ['code' => '516101', 'name' => 'سود و زیان جاری', 'level' => 2, 'parent_id' => $parent516],
                ['code' => '610100', 'name' => 'حقوق ثابت', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610101', 'name' => 'اضافه کار', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610102', 'name' => 'عیدی و پاداش', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610103', 'name' => 'دستمزد کارکنان روزمزد', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610104', 'name' => 'مزایای شغلی', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610105', 'name' => 'حق مسکن', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610106', 'name' => 'حق اولاد', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610107', 'name' => 'خوارو بار', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610108', 'name' => '23% سهم کارفرما', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610109', 'name' => 'بن کارکنان', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610110', 'name' => 'ماموریت کارکنان', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610111', 'name' => 'سنوات خدمت کارکنان', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610112', 'name' => 'حق لباس', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610113', 'name' => 'کسری ابواب جمعی', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610114', 'name' => 'سایر هزینه های پرسنلی', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610115', 'name' => 'حق مسئولیت', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610116', 'name' => '5% محل خدمت', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610117', 'name' => 'بهره وری و کارانه', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610118', 'name' => 'حق شیفت', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610119', 'name' => 'حق نگهبانی', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610120', 'name' => 'حق سرایداری', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610121', 'name' => 'حق غذا', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610122', 'name' => 'ایاب و ذهاب کارکنان', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610123', 'name' => 'حق بدی آب و هوا', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610124', 'name' => 'حق تضمین', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610125', 'name' => 'حق سختی کار', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610126', 'name' => 'مرخصی استفاده نشده', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610127', 'name' => 'کمکهای غیر نقدی', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610128', 'name' => 'بهداشت و درمان', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610129', 'name' => 'بازخرید سنوات خدمت کارکنان', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610130', 'name' => 'آموزش', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610131', 'name' => 'حق شیر', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610132', 'name' => 'حق الزحمه امام جماعت', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610133', 'name' => 'خسارت اخراج', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610134', 'name' => 'کمک هزینه مسکن و بن در ایام بیماری', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610135', 'name' => 'حق تاهل', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '610136', 'name' => 'پایه سنواتی', 'level' => 2, 'parent_id' => $parent610],
                ['code' => '611100', 'name' => 'تعمیر و نگهداری ساختمان و تاسیسات', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611101', 'name' => 'هزینه آب، برق، تلفن، گاز مصرفی', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611102', 'name' => 'تعمیر و نگهداری اثاثه و منصوبات', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611103', 'name' => 'هزینه ملزومات  و نوشت افزار', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611104', 'name' => 'هزینه اجاره انبار و ساختمان ها', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611105', 'name' => 'هزینه ایاب و ذهاب', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611106', 'name' => 'هزینه های حسابرسی', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611107', 'name' => 'پذیرایی و تشریفات', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611108', 'name' => 'بیمه', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611109', 'name' => 'اجاره محل', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611110', 'name' => 'سوخت و سرویس و تعمیرات', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611111', 'name' => 'سایر هزینه های اداری', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611112', 'name' => 'هزینه مطالبات مشکوک الوصول', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611113', 'name' => 'حق جلسات هیئت مدیره', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611114', 'name' => 'هزینه چاپ و نشر و مطبوعات', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611115', 'name' => 'هزینه حق الزحمه', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611116', 'name' => 'هزینه تبایغات و مناسبتها', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611117', 'name' => 'هزینه حق الزحمه مشاورین', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611118', 'name' => 'سهم جاری هزینه تاسیس و قبل از بهره برداری', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611119', 'name' => 'کمک و اعانات', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611120', 'name' => 'هزینه آبدارخانه', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611121', 'name' => 'هزینه نظافت و بهداشت', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611122', 'name' => 'هزینه ایاب و ذهاب هیئت مدیره', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '611123', 'name' => 'هزینه حق عضویت', 'level' => 2, 'parent_id' => $parent611],
                ['code' => '612100', 'name' => 'هزینه تولید', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612110', 'name' => 'هزینه تعمیر و نگهداری ماشین های تولیدی', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612111', 'name' => 'هزینه  انبار داری', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612112', 'name' => 'هزینه سربار', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612113', 'name' => 'هزینه دستمزد مستقیم', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612114', 'name' => 'هزینه مواد مستقیم', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612115', 'name' => 'سایر هزینه های عملیاتی', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612116', 'name' => 'هزینه ضایعات', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612117', 'name' => 'هزینه بیمه دارایی های ثابت', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612118', 'name' => 'هزینه بیمه موجودیها', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612119', 'name' => 'هزینه آب ، برق ، گاز', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612120', 'name' => 'هزینه ملزومات', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612121', 'name' => 'هزینه سوخت کارخانه', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612122', 'name' => 'هزینه پست و تلفن', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612123', 'name' => 'هزینه اجاره محل', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612124', 'name' => 'هزینه تعمیر نگهداری اثاثیه و منسوجات', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612125', 'name' => 'ابزار و لوازم فنی مصرفی', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612126', 'name' => 'تعمیر و نگهداری وسایط نقلیه', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612127', 'name' => 'تعمیر و نگهداری ابزارآلات و قالب ها', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612128', 'name' => 'زیان ناشی از تسعیر ارز', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '612129', 'name' => 'زیان ناشی از اقلام و کالای راکد و ناباب', 'level' => 2, 'parent_id' => $parent612],
                ['code' => '613100', 'name' => 'هزینه ضایعات', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613101', 'name' => 'هزینه های متفرقه توزیع و فروش', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613102', 'name' => 'کارمزد فروشندگان', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613103', 'name' => 'بیمه', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613104', 'name' => 'اجاره محل', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613105', 'name' => 'سوخت و سرویس و تعمیرات', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613106', 'name' => 'هزینه فروشگاه ها', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613107', 'name' => 'هزینه انبار ها', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613108', 'name' => 'هزینه واحد های خدماتی', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613109', 'name' => 'هزینه حمل و نقل', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613110', 'name' => 'هزینه حق العمل کاری', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613111', 'name' => 'سایر هزینه های توزیع و فروش', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613112', 'name' => 'هزینه حمل کالای فروش رفته', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613113', 'name' => 'هزینه های واخواست', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613114', 'name' => 'هزینه سوخت مطالبات', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613115', 'name' => 'هزینه دو در هزار فروش صنایع', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613116', 'name' => 'هزینه شرکت در مزایده', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613117', 'name' => 'هزینه شرکت در مناقصه', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613118', 'name' => 'هزینه های بازاریابی و پورسانت', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613119', 'name' => 'هزینه آگهی و تبلیغات', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '613120', 'name' => 'هزینه ارسال نمونه ها', 'level' => 2, 'parent_id' => $parent613],
                ['code' => '614100', 'name' => 'هزینه سود و کارمزد وامهای دریافتی', 'level' => 2, 'parent_id' => $parent614],
                ['code' => '614101', 'name' => 'هزینه کارمزد خدمات بانکی', 'level' => 2, 'parent_id' => $parent614],
                ['code' => '614102', 'name' => 'هزینه خرید سفته و تمبر', 'level' => 2, 'parent_id' => $parent614],
                ['code' => '614103', 'name' => 'هزینه جریمه دیرکرد وامها', 'level' => 2, 'parent_id' => $parent614],
                ['code' => '614104', 'name' => 'سایر هزینه های مالی', 'level' => 2, 'parent_id' => $parent614],
                ['code' => '614105', 'name' => 'هزینه حق الزحمه مشاورین', 'level' => 2, 'parent_id' => $parent614],
                ['code' => '616100', 'name' => 'هزینه استهلاک ساختمان', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616101', 'name' => 'هزینه استهلاک تاسیسات', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616102', 'name' => 'هزینه استهلاک اثاثیه و منصوبات', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616103', 'name' => 'هزینه استهلاک ابزارآلات', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616104', 'name' => 'هزینه استهلاک وسایل نقلیه', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616105', 'name' => 'هزینه استهلاک ماشین آلات', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616106', 'name' => 'هزینه استهلاک دارایی های زیستی مولد', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616107', 'name' => 'هزینه استهلاک دارایی های زیستی غیر مولد', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '616108', 'name' => 'سایر هزینه های استهلاک', 'level' => 2, 'parent_id' => $parent616],
                ['code' => '617100', 'name' => 'هزینه های خرید', 'level' => 2, 'parent_id' => $parent617],
                ['code' => '618100', 'name' => 'هزینه مطبوعات', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618101', 'name' => 'هزینه رایانه', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618102', 'name' => 'هزینه های اداری و عمومی', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618103', 'name' => 'هزینه ملزومات', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618104', 'name' => 'هزینه ایاب و ذهاب', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618105', 'name' => 'هزینه حقوق و دستمزد', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618106', 'name' => 'هزینه سود پرداختی', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618107', 'name' => 'هزینه استهلاک', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618108', 'name' => 'هزینه های متفرقه', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618109', 'name' => 'هزینه های تمبر مالیاتی', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618110', 'name' => 'هزینه مطالبات مشکوک الوصول', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '618111', 'name' => 'هزینه های مالی', 'level' => 2, 'parent_id' => $parent618],
                ['code' => '619100', 'name' => 'زیان حاصل از فروش داراییها', 'level' => 2, 'parent_id' => $parent619],
                ['code' => '619101', 'name' => 'سایر هزینه های غیر عملیاتی', 'level' => 2, 'parent_id' => $parent619],
                ['code' => '710100', 'name' => 'فروش کالا', 'level' => 2, 'parent_id' => $parent710],
                ['code' => '710101', 'name' => 'فروش متفرقه کالا', 'level' => 2, 'parent_id' => $parent710],
                ['code' => '710102', 'name' => 'فروش محصولات توافقی', 'level' => 2, 'parent_id' => $parent710],
                ['code' => '711100', 'name' => 'برگشت از فروش', 'level' => 2, 'parent_id' => $parent711],
                ['code' => '711101', 'name' => 'برگشت از فروش متفرقه', 'level' => 2, 'parent_id' => $parent711],
                ['code' => '711102', 'name' => 'تخفیفات فروش', 'level' => 2, 'parent_id' => $parent711],
                ['code' => '711103', 'name' => 'تخفیفات فروش متفرقه', 'level' => 2, 'parent_id' => $parent711],
                ['code' => '712100', 'name' => 'درآمد حاصل از خدمات', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712101', 'name' => 'درآمد اجاره', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712102', 'name' => 'درآمد حاصل از کارمزد ها (کمیسیون ها)', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712104', 'name' => 'درآمد یارانه دریافتی', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712105', 'name' => 'درآمد فعالیت های اعتباری', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712106', 'name' => 'درآمد واحد های مکانیزاسیون', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712107', 'name' => 'درآمد حاصل از وسائط نقلیه', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712108', 'name' => 'درآمد حاصل از ماشین آلات', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712109', 'name' => 'سایر درآمد ها', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712110', 'name' => 'سود حاصل از سپرده های بانکی', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712111', 'name' => 'سود حاصل از خرید سهام و سرمایه گذاری', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712112', 'name' => 'فروش ضایعات عادی', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712113', 'name' => 'سود ناشی از تسعیر ارز', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712114', 'name' => 'سود حاصل از فروش مواد اولیه', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712115', 'name' => 'سود حاصل از فروش داراییها', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712116', 'name' => 'سود حاصل ازسرمایه گذاری', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '712117', 'name' => 'سود ناشی از فروش سرمایه گذاری', 'level' => 2, 'parent_id' => $parent712],
                ['code' => '713100', 'name' => 'درآمد قرض الحسنه', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713101', 'name' => 'درآمد مبادلات', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713102', 'name' => 'درآمد مشارکت', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713103', 'name' => 'درآمد تعهدات', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713105', 'name' => 'سود سپرده گذاری در بانکها', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713106', 'name' => 'درآمد های خدماتی', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713107', 'name' => 'درآمد معوقه تسهیلات', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713108', 'name' => 'درآمد های متفرقه', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713113', 'name' => 'درآمد تعهدی قرض الحسنه', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713114', 'name' => 'درآمد تعهدی مبادلات', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713115', 'name' => 'درآمد تعهدی مشارکت', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713116', 'name' => 'درآمد تعهدی تعهدات', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '713117', 'name' => 'درآمد مازاد سود برگشتی سپرده ها', 'level' => 2, 'parent_id' => $parent713],
                ['code' => '810100', 'name' => 'بهای تمام شده کالای فروش رفته', 'level' => 2, 'parent_id' => $parent810],
                ['code' => '810101', 'name' => 'بهای تمام شده کالای فروش رفته ساخته شده', 'level' => 2, 'parent_id' => $parent810],
                ['code' => '910100', 'name' => 'خلاصه سود و زیان', 'level' => 2, 'parent_id' => $parent910],
                ['code' => '910101', 'name' => 'طرف حساب انتظامی', 'level' => 2, 'parent_id' => $parent910],
                ['code' => '910102', 'name' => 'حساب انتظامی', 'level' => 2, 'parent_id' => $parent910],
                ['code' => '910103', 'name' => 'حساب ترازنامه ای', 'level' => 2, 'parent_id' => $parent910],
            ],
            ['code'],
            ['name', 'level', 'parent_id']
        );
    }
}
